// Generated by CoffeeScript 2.7.0
var showConfirmDialog, showDialog;

showDialog = function(message) {
  var dialog, okBtn;
  dialog = document.createElement('dialog');
  dialog.style.fontWeight = '400';
  dialog.style.fontFamily = 'Arial, sans-serif';
  if (window.innerWidth > 400) {
    dialog.style.maxWidth = '400px';
  }
  dialog.style.borderRadius = '15px';
  dialog.style.overflow = 'hidden'; // optional, to clip content
  dialog.style.border = '1px solid #000'; //'1px solid #ccc'
  dialog.style.boxShadow = '0 4px 16px rgba(0,0,0,.2)';
  dialog.innerHTML = `${message}
<br>
<center>
  <button id="okBtn">OK</button>
</center>`;
  document.body.appendChild(dialog);
  dialog.showModal();
  okBtn = dialog.querySelector('#okBtn');
  okBtn.style.fontSize = '16px';
  okBtn.style.padding = '2px 15px';
  return okBtn.onclick = function() {
    dialog.close();
    return dialog.remove();
  };
};

// --------------------------------------
showConfirmDialog = function(message) {
  var cancelBtn, dialog, okBtn;
  dialog = document.createElement('dialog');
  dialog.style.borderRadius = '15px';
  dialog.style.overflow = 'hidden'; // optional, to clip content
  dialog.style.border = '1px solid #000'; //'1px solid #ccc'
  dialog.style.boxShadow = '0 4px 16px rgba(0,0,0,.2)';
  dialog.innerHTML = `${message}
<br>
<center>
  <button id="okBtn">Oui</button>&ensp;&ensp;
  <button id="cancelBtn">Non</button>
</center>`;
  // OK button
  okBtn = dialog.querySelector('#okBtn');
  okBtn.style.padding = '2px 15px';
  okBtn.style.fontSize = '16px';
  okBtn.onclick = function() {
    dialog.returnValue = 'ok';
    dialog.close();
    return dialog.remove();
  };
  // Cancel button
  cancelBtn = dialog.querySelector('#cancelBtn');
  cancelBtn.style.padding = '2px 15px';
  cancelBtn.style.fontSize = '16px';
  cancelBtn.onclick = function() {
    dialog.close();
    return dialog.remove();
  };
  document.body.appendChild(dialog);
  dialog.showModal();
  // Return Promise for async result
  return new Promise(function(resolve) {
    return dialog.onclose = function() {
      var result;
      result = dialog.returnValue;
      return resolve(result === 'ok');
    };
  });
};

//# sourceMappingURL=dialogs.js.map
